version: 2.0.{build}

branches:
  only:
  - clientWindows

shallow_clone: true

configuration: Release

platform: x64

init:
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

install:
  - ps: Get-NodeJsLatestBuild 7.9
  - ps: Install-Product node 7.9.0 x64
  - dir C:\avvm\node
  - node -v
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd client
  - npm install --production --msvs_version=2013
  - npm run update
  - npm run build_win
  - ren SAGE2_client-win32-x64 SAGE2_client-%APPVEYOR_BUILD_VERSION%
  - 7z a -sfx7z.sfx SAGE2_client-%APPVEYOR_BUILD_VERSION%.exe SAGE2_client-%APPVEYOR_BUILD_VERSION% > nul
  - move SAGE2_client-%APPVEYOR_BUILD_VERSION%.exe ..

build: off

test: off

artifacts:
  - path: SAGE2_client-$(APPVEYOR_BUILD_VERSION).exe
    name: sage2_client

deploy:
  - provider: FTP
    host: ftp.sagecommons.org
    protocol: ftp
    username: upload@sagecommons.org
    password:
      secure: L4I4NkKN7mrQww7GgwPLrA==
    folder: /
    artifact: sage2_client

notifications:
  - provider: Slack
    channel: '#appveyor'
    auth_token:
      secure: zWPzLLrh/2HV3lXJd9q5XHTy015slI7x1ptyvmOARG2TXpeftHtzKbtzxufzpVBirSHrvr95vgBR+ouSX+KQHceIPeAXEJEBXvA7wHZS7ng=
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

