version: 2.0.{build}

branches:
  only:
  - master

shallow_clone: true

configuration: Release

platform: x64

init:
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

install:
  - ps: Get-NodeJsLatestBuild 7.9
  - ps: Install-Product node 7.9.0 x64
  - dir C:\avvm\node
  - node -v
  - cd %APPVEYOR_BUILD_FOLDER%
  - npm install --production --msvs_version=2013
  - npm install npm
  - npm install -g kthxbai
  - kthxbai

build: off

test: off

artifacts:
  - path: SAGE2_client-win32-x64.zip
    name: sage2-win64

deploy:
  - provider: FTP
    host: ftp.sagecommons.org
    protocol: ftp
    username: upload@sagecommons.org
    password:
      secure: L4I4NkKN7mrQww7GgwPLrA==
    folder: /
    artifact: sage2-win64

notifications:
  - provider: Slack
    channel: '#appveyor'
    auth_token:
      secure: zWPzLLrh/2HV3lXJd9q5XHTy015slI7x1ptyvmOARG2TXpeftHtzKbtzxufzpVBirSHrvr95vgBR+ouSX+KQHceIPeAXEJEBXvA7wHZS7ng=
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

