version: 0.3.{build}

branches:
  only:
  - master

# git clone of depth 1
# clone_depth: 1

# specific to github and bitbucket: get a ZIP file using REST API
shallow_clone: true

configuration: Release

platform: x64

init:
  - curl -LsSO http://ffmpeg.zeranoe.com/builds/win64/dev/ffmpeg-20150806-git-9c0407e-win64-dev.7z
  - 7z x ffmpeg-20150806-git-9c0407e-win64-dev.7z -o.
  - mkdir C:\Dev\
  - mkdir C:\Dev\ffmpeg-win64-dev
  - move ffmpeg-20150806-git-9c0407e-win64-dev\lib C:\Dev\ffmpeg-win64-dev
  - move ffmpeg-20150806-git-9c0407e-win64-dev\include C:\Dev\ffmpeg-win64-dev
  - del /Q *.7z
  - rmdir /Q /S ffmpeg-20150806-git-9c0407e-win64-dev
  - dir C:\Dev
  - dir C:\Dev\ffmpeg-win64-dev\include
  - dir C:\Dev\ffmpeg-win64-dev\lib

install:
  - ps: Install-Product node 0.12.7 x64
  - npm -v
  - node -v
  - npm install --production --msvs_version=2013
  - npm install -g kthxbai
  - kthxbai
  - curl -LsSO http://ffmpeg.zeranoe.com/builds/win64/shared/ffmpeg-20150806-git-9c0407e-win64-shared.7z
  - 7z x ffmpeg-20150806-git-9c0407e-win64-shared.7z -o.
  - copy ffmpeg-20150806-git-9c0407e-win64-shared\bin\*.dll node_modules\node-demux\build\Release
  - copy ffmpeg-20150806-git-9c0407e-win64-shared\bin\*.dll bin\
  - copy ffmpeg-20150806-git-9c0407e-win64-shared\bin\*.exe bin\
  - rmdir /Q /S ffmpeg-20150806-git-9c0407e-win64-shared
  - curl -LsSO http://www.sno.phy.queensu.ca/~phil/exiftool/exiftool-9.99.zip
  - 7z x exiftool-9.99.zip
  - move exiftool(-k).exe bin\exiftool.exe
  - del /Q *.7z
  - del /Q *.zip
  - 7z a -tzip sage2-%APPVEYOR_BUILD_VERSION%.zip AUTHORS GO-scripts Gruntfile.js LICENSE.txt README.md bin config doc install_dependencies.js keys node_modules package.json public server.js sessions src

build: off

test: off

artifacts:
  - path: sage2-$(APPVEYOR_BUILD_VERSION).zip
    name: sage2-win64

deploy:
  - provider: FTP
    host: ftp.evl.uic.edu
    protocol: ftp
    username: anonymous
    password:
      secure: l0HiJIV16DR1bWNu033KVw==
    folder: pub/INcoming/luc/app
    artifact: sage2-win64

after_deploy:
  - dir

notifications:
  - provider: Slack
    auth_token:
      secure: zWPzLLrh/2HV3lXJd9q5XK+m2D1zn/bWBIQOzjQ2QkFSFL3ijB839EMqTRUrYZeA
    channel: appveyor
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

