# This is a sample build configuration for Javascript.
# Only use spaces to indent your .yml configuration.
# You can specify a custom docker image from Dockerhub as your build environment.
image: node:latest

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - npm --version
          - npm install --only=dev
          - npm run lint
          - npm run doc
